				</div>
				<!--<div class="aside">
					<h3>Sidebar</h3>
					<p>Ut wisi enim ad minim veniam, <a href="#">quis nostrud exerci tation ullamcorper</a> suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
				</div>-->
			</div>
		</div>
		<div class="footer">
			<div class="container" align="left">
				<i><small>
				Generated by <a href="http://autoredistrict.org">Auto-Redistrict</a>.
				</small></i>
			</div>
		</div>
	</body>
</html>